/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    Button: typeof import('primevue/button')['default']
    DisplayPage: typeof import('./src/components/DisplayPage.vue')['default']
    DisplayProductsList: typeof import('./src/components/product/DisplayProductsList.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    ElementNotFound: typeof import('./src/components/ElementNotFound.vue')['default']
    ErrorMessageField: typeof import('./src/components/ErrorMessageField.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HoveredLink: typeof import('./src/components/gsap-test/HoveredLink.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Main: typeof import('./src/views/Home.vue')['default']
    MainLayout: typeof import('./src/layouts/MainLayout.vue')['default']
    Menu: typeof import('./src/components/gsap-test/Menu.vue')['default']
    MenuItem: typeof import('./src/components/gsap-test/MenuItem.vue')['default']
    NavBar: typeof import('./src/components/gsap-test/NavBar.vue')['default']
    Password: typeof import('primevue/password')['default']
    Product: typeof import('./src/components/product/Product.vue')['default']
    ProductCard: typeof import('./src/components/product/list/ProductCard.vue')['default']
    ProductItem: typeof import('./src/components/gsap-test/ProductItem.vue')['default']
    ProductsList: typeof import('./src/components/product/ProductsList.vue')['default']
    ProductsListComponent: typeof import('./src/components/product/list/ProductsListComponent.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RegisterComponent: typeof import('./src/components/auth/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SingleProduct: typeof import('./src/components/product/SingleProduct.vue')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
