/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    DisplayPage: typeof import('./src/components/DisplayPage.vue')['default']
    DisplayProductsList: typeof import('./src/components/product/DisplayProductsList.vue')['default']
    ElementNotFound: typeof import('./src/components/ElementNotFound.vue')['default']
    ErrorMessageField: typeof import('./src/components/ErrorMessageField.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HoveredLink: typeof import('./src/components/gsap-test/HoveredLink.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    LoginComponent: typeof import('./src/components/auth/LoginComponent.vue')['default']
    Main: typeof import('./src/views/Home.vue')['default']
    MainLayout: typeof import('./src/layouts/MainLayout.vue')['default']
    Menu: typeof import('./src/components/gsap-test/Menu.vue')['default']
    MenuItem: typeof import('./src/components/gsap-test/MenuItem.vue')['default']
    Product: typeof import('./src/components/product/Product.vue')['default']
    ProductCard: typeof import('./src/components/product/list/ProductCard.vue')['default']
    ProductItem: typeof import('./src/components/gsap-test/ProductItem.vue')['default']
    ProductsList: typeof import('./src/components/product/ProductsList.vue')['default']
    ProductsListComponent: typeof import('./src/components/product/list/ProductsListComponent.vue')['default']
    RegisterComponent: typeof import('./src/components/auth/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleProduct: typeof import('./src/components/product/SingleProduct.vue')['default']
  }

}
